version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: premier_pas_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
